version: "3.4"

services:
    wordpress: 
        image: wordpress
        ports:
            - 8080:80
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: testedcc
        volumes:
            - "./wordpress-data:/var/www/html"

    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: testedcc
        volumes:
            - "./mysql-data:/var/lib/mysql"